### ISSUE TITLE
Is the libyp.so same to this yp-tools？And how to build the yp-tools source code to get a .so file?

### ISSUE THREAD

**Issue by Alice-Meng** [thkukuk/yp-tools#11]
When I build Python3.11，nis module is missing. And I searched the internet, I found I should install libyp.so and libnsl.so. I tried use the command 'yum install -y libyp-devel', not found libyp-devel. So I tried to build this yp-tools sourcecode，but I still don't get a libyp.so. Are they the same library? How should I get a libyp.so?

(The architecture of my system is Linux aarch64.)

**Comment by thkukuk** [comment]
No, yp-tools don't provide libyp.so nor any other shared library.
This is something you should ask your Linux distributor.
