### ISSUE TITLE
yptest no longer installed

### ISSUE THREAD

**Issue by pkubatrh** [thkukuk/yp-tools#4]
Fedora has recently updated to latest yp-tools and it seems the `yptest` binary has been moved from `sbin_PROGRAMS` to `EXTRA_PROGRAMS` and later on to `check_PROGRAMS` (https://github.com/thkukuk/yp-tools/commit/425b724cc9e5d5449acef518b347f993b17e0c4c#diff-480477e89f9b6ddafb30c4383dcdd705R15), making it not installable anymore by default.

I think having `yptest` available outside of `make check` would be nice to have for NIS admins to check whether everything is configured correctly, and there are some other users that would welcome it back as well (https://bugzilla.redhat.com/show_bug.cgi?id=1520600). Would it be possible make it installable again? Maybe through some configuration switch if not by default.

**Comment by thkukuk** [comment]
I adjusted yptest to build again with old glibc/sunrpc combo and install it per default
