### ISSUE TITLE
Changing password to an user using yppasswd with ! in /etc/shadow

### ISSUE THREAD

**Issue by Lupphes** [thkukuk/yp-tools#9]
If a user has an exclamation mark (!) or possibly star (*) flag in their hashed password in /etc/shadow, the yppasswd will segfault. Those symbols are not the actual passwords of the user but rather flags of the account. See example:
```
$ ypcat passwd
fedora:!!:1000:1000:fedora cld:/home/fedora:/bin/bash
```
```
Changing NIS password for fedora on XYZ.
Please enter new password:
Segmentation fault (core dumped)
```

The segmentation fault occurs when the `crypt()` function in `verifypassword()` in `v4.2.3/yp-tools-4.2.3/src/yppasswd.c` receives previous password (salt) as a `!!` which is undefined behavior and the crypt function returns NULL. The two exclamation marks symbolize a locked account (account with no initialized password).
[RedHat user add process](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/4/html/system_administration_guide/s2-redhat-config-users-process)

There are two possibilities of how the issue can be fixed:
1. Detect the `!` in /etc/passwd, inform the user and exit the script without password change.
2. Let the user set the password if `!` is detected. This solution brings potential problems with validating users and changing unset root passwords.

What approach should be chosen when sorting this bug? More info about this issue is here: [Red Hat Bugzilla ticket](https://bugzilla.redhat.com/show_bug.cgi?id=2093381).

**Comment by thkukuk** [comment]
None of the two, use PAM for this task. Either let yppasswd call passwd like SUSE is doing, or don't ship yppasswd and tell the user to use passwd direct instead.

**Comment by Lupphes** [comment]
Thank you for your response. I fixed the issues using the `YPPASSWD_IS_DEPRECATED=1` flag when a building like OpenSUSE is doing.  
The issue is resolved.
